# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-04 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='blog'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=uuid.uuid4, unique=True),
        ),
    ]
