# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=50, unique=True)),
                ('slug', models.SlugField(default=uuid.uuid4, unique=True)),
                ('service_desc', models.TextField()),
                ('service_headline', models.CharField(max_length=250)),
                ('service_image', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Services',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='ServicesLandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('services_headline', models.CharField(max_length=250)),
                ('services_desc', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
                'verbose_name': 'Services Landing Page',
                'verbose_name_plural': 'Services Landing Page',
            },
        ),
    ]
