# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 03:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumtrack',
            name='track_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
