# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0002_auto_20170312_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='mini_music_img',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
