# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 01:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0002_albumtrack_track_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='market_place',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
