# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0002_auto_20161210_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='service_desc',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_headline',
            new_name='headline',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='service_image',
            new_name='image',
        ),
    ]
