# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 01:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0003_auto_20161211_0125'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='about')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
                'verbose_name_plural': 'About',
                'verbose_name': 'About',
            },
        ),
    ]
