# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-21 04:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0003_home_mini_music_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaURLs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(max_length=350)),
                ('twitter', models.URLField(max_length=350)),
                ('youtube', models.URLField(max_length=350)),
                ('instagram', models.URLField(max_length=350)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Social Media URLS',
                'verbose_name': 'Social Media URL',
                'get_latest_by': 'timestamp',
            },
        ),
    ]
