# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-06 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0003_album_market_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='market_place',
            field=models.URLField(blank=True, max_length=250),
        ),
    ]
