# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0004_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='summary',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
