# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-05-14 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0005_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='location',
            field=models.TextField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
