# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0005_about_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about/albumns')),
            ],
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.ImageField(upload_to='services'),
        ),
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.ImageField(upload_to='services'),
        ),
    ]
