# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sws_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0006_auto_20161211_0739'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('track', models.FileField(upload_to=sws_site.models.get_track_upload_path)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='image',
            field=models.ImageField(upload_to=sws_site.models.get_upload_path),
        ),
        migrations.AddField(
            model_name='albumtrack',
            name='albumn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sws_site.Album'),
        ),
    ]
