# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-11 08:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0007_auto_20161211_0819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albumtrack',
            old_name='albumn',
            new_name='album',
        ),
    ]
