# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import sws_site.models


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0009_remove_albumtrack_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumtrack',
            name='track_name',
            field=models.FileField(default=django.utils.timezone.now, upload_to=sws_site.models.get_file_name),
            preserve_default=False,
        ),
    ]
