# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0011_remove_albumtrack_track_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumtrack',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='sws_site.Album'),
        ),
    ]
