# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-31 06:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0013_about_home_page_headline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='home_page_headline',
            new_name='homepage_headline',
        ),
    ]
