# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 07:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sws_site', '0016_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='mini_music_description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='mini_music_headline',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
